### ISSUE TITLE
AppInsights API key already in use

### ISSUE THREAD

**Issue by jmezach** [areve/IframeDashboardWidget#4]
Hi there,

I noticed that the API key you are using for Application Insights is the same key that I'm using for [NewRelicDashboardWidgets](https://github.com/jmezach/NewRelicDashboardWidgets). Would you mind changing this so I don't get telemetry from your extension into my AppInsights instance ;).

Greetings,

Jonathan

**Comment by areve** [comment]
I'll certainly look into this

**Comment by areve** [comment]
Jonathan,

I've update the widget, sorry about this it was because I didn't really
know what I was doing when I wrote this. Thanks for helping by making your
widget open source:) and for letting me know of this problem.

Andrew

**Comment by jmezach** [comment]
No problem, glad we got this sorted now :).
